<div style="clear: both"></div>
<h2>List of Exhibits</h2>
<ul>
<?php
$exhibits = $this->exhibits + $this->siblings;
if (! $this->include_self){
    unset($exhibits[$this->current_page]);
}
foreach ($exhibits as $page_id => $preview) : ?>

    <li style="list-style: none">
        <div style="background: whitesmoke; width: 300px;">

            <a href="<?php echo $preview['url']; ?>">
                <img alt="<?php echo $preview['alt'] ?>" src="<?php echo $preview['img_src'] ?>" style="max-width: 300px;"/>
            </a>
            <h3>
                <a href="<?php echo $preview['url']; ?>"><?php echo $preview['title']; ?></a>
            </h3>
        </div>

    </li>
<?php endforeach; ?>
</ul>

