<h2>Mason List of Exhibits: Test View</h2>
<p>here are page id's based on the depth the user indicated for exhibits</p>
<p>the other form options (Include all Omeka-s exhibits, Include other sites, team) aren't hooked up to anything yet</p>
<p>here is the array that is being passed right now</p>
<ul>
<?php
foreach ($this->exhibits as $key => $value):
echo '<li>page id: ' . $key . " has depth of " . $value . '</li>';
endforeach;
?>
</ul>